DDS.WebApp.PSQuoteGenerator/Controllers/QuoteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using AutoMapper;
using DDS.Core.BusinessLayer.Methods.QuoteManagement;
using DDS.Core.BusinessObjects.Quote;
using DDS.Core.BusinessObjects.Technology;
using DDS.Core.DataLayer;
using DDS.WebApp.PSQuoteGenerator.Models;
using Rotativa;
using Rotativa.Options;
using WebGrease.Css.Ast.Selectors;

namespace DDS.WebApp.PSQuoteGenerator.Controllers
{
    public class QuoteController : Controller
    {

        private readonly QuoteManagement _manager = new QuoteManagement();

        // GET: Quote
        public ActionResult Index()
        {
            var model = Mapper.Map<List<Quote>, List<QuoteModel>>(_manager.GetQuotes());
            return View(model);
        }

        public FileResult Download(string file)
        {

            try
            {
                var u = new Uri(file);
                var fileName = string.Empty;

                if (u.IsFile)
                    fileName = Path.GetFileName(u.AbsolutePath);

                var fileBytes = System.IO.File.ReadAllBytes(file);
                var response = new FileContentResult(fileBytes, "application/octet-stream")
                {
                    FileDownloadName = fileName
                };
                return response;
            }
            catch (Exception)
            {
                return null;
            }
        }

        // GET: Quote/Create
        public ActionResult Create()
        {
            ViewBag.Client = new SelectList(_manager.GetClients(), "Id", "CombinedName");
            return View();
        }

        // POST: Quote/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,QuoteName,QuoteDesc,Client,QuoteRefNumber")] QuoteModel quoteModel)
        {
            ViewBag.Client = new SelectList(_manager.GetClients(), "Id", "CombinedName", quoteModel.Client);
            
            if (ModelState.IsValid)
            {
                var proposalFile = Request.Files["ProposalPath"];
                if (proposalFile != null && proposalFile.ContentLength > 0)
                {
                    const string path = @"C:\QuoteProposals\";

                    if (proposalFile.ContentLength > 4194304)
                    {
                        ModelState.AddModelError("ProposalPath", "The size of the file should not exceed 4 MB");
                        return View(quoteModel);
                    }

                    var supportedTypes = new[] { "doc", "docx" };

                    var extension = Path.GetExtension(proposalFile.FileName);
                    if (extension != null)
                    {
                        var fileExt = extension.Substring(1);

                        if (!supportedTypes.Contains(fileExt))
                        {
                            ModelState.AddModelError("ProposalPath", "Invalid type. Only the following types (doc, docx) are supported.");
                            return View(quoteModel);
                        }

                        var cleanRef = quoteModel.QuoteRefNumber.Replace(":", string.Empty).Replace("\\", string.Empty).Replace("/", string.Empty);
                        var newFileName = "Proposal-" + cleanRef + " " + DateTime.Now.ToString("yyyyMMddhhmmss") + "." + fileExt;
                        var proposalPath = path + newFileName;
                        proposalFile.SaveAs(proposalPath);

                        quoteModel.ProposalPath = proposalPath;
                    }

                    
                }

                var model = Mapper.Map<QuoteModel, Quote>(quoteModel);

                var inserted = _manager.InsertQuote(model);

                if (inserted == 0)
                {
                    RedirectToAction("Index");
                }

                return RedirectToAction("TechnologySelection", new { id = inserted });
            }

            
            return View(quoteModel);
        }

        // GET: Quote/TechnologySelection/5
        public ActionResult TechnologySelection(int id)
        {
            ViewBag.SelectedTechnologies = new MultiSelectList(_manager.GetTechnologies(), "Id", "TechnologyName");
            
            return View();
        }

        // POST: Quote/TechnologySelection/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TechnologySelection([Bind(Include = "Id,SelectedTechnologies")] QuoteTechnologyModel technologies)
        {
            ViewBag.SelectedTechnologies = new MultiSelectList(_manager.GetTechnologies(), "Id", "TechnologyName", technologies.SelectedTechnologies);
            if (technologies.SelectedTechnologies == null)
            {
                ModelState.AddModelError("SelectedTechnologies", "Please select atleast one Technology");
                return View();
            }

            if (technologies.SelectedTechnologies.Count > 0)
            {
                TempData["complexityModel"] = _manager.GetComplexities(technologies.SelectedTechnologies);

                var savedQuoted = _manager._db.Quotes.Find(technologies.Id);
                savedQuoted.PhysicalDevices = technologies.SelectedTechnologies.Count;
                _manager._db.SaveChanges();

                return RedirectToAction("TechnologyComplexity", new {id = technologies.Id});
            }

            return View();
        }

        // GET: Quote/TechnologyComplexity/5
        public ActionResult TechnologyComplexity(int id)
        {
            var complexities = (List<ComplexityObj>)TempData["complexityModel"];
            var model = Mapper.Map<List<ComplexityObj>, List<QuoteTechnologyComplexity>>(complexities);
            return View(model);
        }

        // POST: Quote/TechnologyComplexity/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TechnologyComplexity([Bind(Include = "Id,Options")] QuoteTechnologyComplexity complexities)
        {
            var manualIds = new List<int>();
            var complexStepsFound = false;
            var projectTypeTechnologyCombo = new List<QuoteCombo>();
            var nacTechologies = new List<AdditionalDataModel>();

            foreach (var option in complexities.Options)
            {
                var currentTechnology = int.Parse(option.Substring(0, option.IndexOf('-')));
                var currentProjectType = int.Parse(option.Substring(option.IndexOf('-') + 1));
                var currentCombo = new QuoteCombo()
                {
                    CurrentProjectType = currentProjectType,
                    CurrentTechnology = currentTechnology
                };
                projectTypeTechnologyCombo.Add(currentCombo);

                if (currentProjectType != 555)
                {
                    _manager.InsertLineItems(currentTechnology, currentProjectType, complexities.Id);

                    //check for complex steps
                    var complexSteps =_manager._db.ComplexSteps.Where(cs => cs.Technology == currentTechnology && cs.ProjectType == currentProjectType).ToList();

                    if (complexSteps.Count > 0)
                    {
                        complexStepsFound = true;
                    }

                }
                else if (currentProjectType == 555)
                {
                    manualIds.Add(currentTechnology);
                }

                //check for Standard NAC technologies to determine wheter or not to ask about Nodes,VLANs and SSIDs
                //check technology category
                var technologies =_manager._db.Technologies.Find(currentTechnology);

                if (technologies.TechnologyCategory != 3 && currentProjectType != 3) continue;

                var nacTech = new AdditionalDataModel()
                {
                    TechnologyId = technologies.Id,
                    QuoteId = complexities.Id,
                    Technology = technologies
                };
                nacTechologies.Add(nacTech);
            }

            if (nacTechologies.Count > 0)
            {
                if (manualIds.Count > 0)
                {
                    System.Web.HttpContext.Current.Session["ManualIds"] = manualIds;
                }

                if (complexStepsFound)
                {
                    System.Web.HttpContext.Current.Session["quoteCombo"] = projectTypeTechnologyCombo;
                }

                System.Web.HttpContext.Current.Session["NACTechnologies"] = nacTechologies;
                return RedirectToAction("ProcessNacVariables", new { id = complexities.Id });
            }

            if (complexStepsFound)
            {
                //TempData["quoteCombo"] = projectTypeTechnologyCombo;
                System.Web.HttpContext.Current.Session["quoteCombo"] = projectTypeTechnologyCombo;

                if (manualIds.Count > 0)
                {
                    System.Web.HttpContext.Current.Session["ManualIds"] = manualIds;
                }

                return RedirectToAction("ProcessComplexSteps", new { id = complexities.Id});
            }

            if (manualIds.Count > 0)
            {
                System.Web.HttpContext.Current.Session["ManualIds"] = manualIds;
                return RedirectToAction("ProcessManualSteps", new {id = complexities.Id});
            }

            _manager._db.Quotes.Find(complexities.Id).Status = "STEPS SELECTED";
            _manager._db.SaveChanges();

            return RedirectToAction("ProcessAdditional", new { id = complexities.Id });

DDS.WebApp.PSQuoteGenerator/Controllers/StepController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using DDS.Core.BusinessLayer.Methods.ProjectConfiguration;
using DDS.Core.DataLayer;
using DDS.WebApp.PSQuoteGenerator.Models;


namespace DDS.WebApp.PSQuoteGenerator.Controllers
{
    public class StepController : Controller
    {
        private readonly StepConfiguration _manager = new StepConfiguration();

        // GET: Step/Setup
        public ActionResult Setup()
        {
            ViewBag.Technology = new SelectList(_manager.Db.Technologies, "Id", "TechnologyName");
            ViewBag.ProjectType = new SelectList(_manager.GetProjectTypes(), "Id", "ProjectType1");

            return View();
        }

        // POST: Step/Setup
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Setup(FormCollection formCollection)
        {
            var tech = int.Parse(formCollection["Technology"]);
            System.Web.HttpContext.Current.Session["CurrentTechnologyId"] = tech;

            System.Web.HttpContext.Current.Session["CurrentTechnologyName"] = _manager.Db.Technologies.Find(tech).TechnologyName;

            var projType = int.Parse(formCollection["ProjectType"]);
            System.Web.HttpContext.Current.Session["CurrentProjectType"] = projType;

            System.Web.HttpContext.Current.Session["currentProjTypeString"] = _manager.Db.ProjectTypes.Find(projType).ProjectType1;

            return RedirectToAction("index");
        }

        // GET: Step
        public ActionResult Index()
        {

            var currentTech = System.Web.HttpContext.Current.Session["CurrentTechnologyId"] is int ? (int)System.Web.HttpContext.Current.Session["CurrentTechnologyId"] : 0;
            var currentProjType = System.Web.HttpContext.Current.Session["CurrentProjectType"] is int ? (int)System.Web.HttpContext.Current.Session["CurrentProjectType"] : 0;

            if (currentTech == 0 || currentProjType == 0)
            {
                return RedirectToAction("Setup");
            }

            var steps = Mapper.Map<List<Step>, List<StepModel>>(_manager.GetSteps(currentTech, currentProjType));

            return View(steps);
        }

        // GET: Step/Create
        public ActionResult Create()
        {
            var currentTech = System.Web.HttpContext.Current.Session["CurrentTechnologyId"] is int ? (int)System.Web.HttpContext.Current.Session["CurrentTechnologyId"] : 0;
            var currentProjType = System.Web.HttpContext.Current.Session["CurrentProjectType"] is int ? (int)System.Web.HttpContext.Current.Session["CurrentProjectType"] : 0;

            ViewBag.Technology = new SelectList(_manager.Db.Technologies, "Id", "TechnologyName", currentTech);
            ViewBag.EngineeringLevel = new SelectList(_manager.Db.Engineers, "Id", "EngineeringLevel");
            ViewBag.ProjectType = new SelectList(_manager.GetProjectTypes(), "Id", "ProjectType1", currentProjType);

            return View();
        }

        // POST: Step/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,StepDescription,EngineeringLevel,Hours,Technology,ProjectType")] StepModel stepModel)
        {
            if (ModelState.IsValid)
            {
                var model = Mapper.Map<StepModel, Step>(stepModel);

                var inserted = _manager.InsertStep(model);

                if (inserted)
                {
                    return RedirectToAction("Index");
                }
            }

            ViewBag.Technology = new SelectList(_manager.Db.Technologies, "Id", "TechnologyName", stepModel.Technology);
            ViewBag.EngineeringLevel = new SelectList(_manager.Db.Engineers, "Id", "EngineeringLevel", stepModel.EngineeringLevel);
            ViewBag.ProjectType = new SelectList(_manager.GetProjectTypes(), "Id", "ProjectType1", stepModel.ProjectType);

            return View(stepModel);
        }

        // GET: Step/Edit/5
        public ActionResult Edit(int id)
        {
            var step = Mapper.Map<Step, StepModel>(_manager.GetStepById(id));
            if (step == null)
            {
                return HttpNotFound();
            }
            ViewBag.Technology = new SelectList(_manager.Db.Technologies, "Id", "TechnologyName", step.Technology);
            ViewBag.EngineeringLevel = new SelectList(_manager.Db.Engineers, "Id", "EngineeringLevel", step.EngineeringLevel);
            ViewBag.ProjectType = new SelectList(_manager.GetProjectTypes(), "Id", "ProjectType1", step.ProjectType);

            return View(step);
        }

        // POST: Step/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StepDescription,EngineeringLevel,Hours,Technology,ProjectType")] StepModel stepModel)
        {
            if (ModelState.IsValid)
            {
                var model = Mapper.Map<StepModel, Step>(stepModel);

                var updated = _manager.UpdateStep(model);
                if (updated)
                {
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Technology = new SelectList(_manager.Db.Technologies, "Id", "TechnologyName", stepModel.Technology);
            ViewBag.EngineeringLevel = new SelectList(_manager.Db.Engineers, "Id", "EngineeringLevel", stepModel.EngineeringLevel);
            ViewBag.ProjectType = new SelectList(_manager.GetProjectTypes(), "Id", "ProjectType1",stepModel.ProjectType);

            return View(stepModel);
        }

        // GET: Step/Delete/5
        public ActionResult Delete(int id)
        {
            var step = Mapper.Map<Step, StepModel>(_manager.GetStepById(id));
            if (step == null)
            {
                return HttpNotFound();
            }
            return View(step);
        }

        // POST: Step/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (_manager.RemoveStep(id))
            {
                return RedirectToAction("Index");
            }
            return View(id);
        }

        public void UpdateStepNumber(int id, int fromPosition, int toPosition, string direction, int tech, int projType)
        {
            
            if (direction == "back")
            {
                var movedSteps = _manager.Db.Steps.Where(t => t.Technology == tech && t.ProjectType == projType).Where(c => (toPosition <= c.StepNumber && c.StepNumber <= fromPosition)).ToList();

                foreach (var step in movedSteps)
                {
                    step.StepNumber++;
                        
                }
            }
            else
            {
                var movedSteps = _manager.Db.Steps.Where(t => t.Technology == tech && t.ProjectType == projType).Where(c => (fromPosition <= c.StepNumber && c.StepNumber <= toPosition)).ToList();
                foreach (var step in movedSteps)
                {
                    step.StepNumber--;
                        
                }
            }

            _manager.Db.Steps.First(c => c.Id == id).StepNumber = toPosition;
            _manager.Db.SaveChanges();

        }
    }
}

DDS.WebApp.PSQuoteGenerator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Dimension Data PS Quote Generator</title>
    @Styles.Render("~/bundles/css")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Scripts")
    <script src="~/Scripts/bootstrap-formhelpers.js"></script>
    <link href="~/Content/bootstrap-formhelpers.css" rel="stylesheet" />
    <meta name="description" content="Dimension Data PS Quote Generator" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PS Quote Generator", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="margin-top: 0;">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Project Configuration<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                
                                <li>@Html.ActionLink("Client Configuration", "Index", "Client")</li>
                                <li>@Html.ActionLink("Engineer Configuration", "Index", "Engineer")</li>
                                <li>@Html.ActionLink("Manager Configuration", "Index", "Manager")</li>
                                <li>@Html.ActionLink("Manual Step Configuration", "Index", "ManualStep")</li>
                                <li>@Html.ActionLink("Preconfigured Step Configuration", "Setup", "Step")</li>
                                <li>@Html.ActionLink("PM Deliverable Configuration", "Index", "PMDeliverable")</li>
                                <li>@Html.ActionLink("Sundry Cost Configuration", "Index", "SundryCost")</li>
                                <li>@Html.ActionLink("Technology Configuration", "Index", "Technology")</li>
                                
                            </ul>
                        </li>
                    }
                    @if (Request.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Quote<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                @*@if (User.IsInRole("Pre-Sale Engineer"))
                                {
                                    <li>@Html.ActionLink("Create New Quote", "Create", "Quote")</li>
                                }
                                @if (User.IsInRole("Manager"))
                                {
                                    <li>@Html.ActionLink("Find Quote", "Index", "Quote")</li>
                                }
                                <li>@Html.ActionLink("Task List", "Index", "Task")</li>*@
                                <li>@Html.ActionLink("Create Quote", "Create", "Quote")</li>
                                <li>@Html.ActionLink("View Quotes", "Index", "Quote")</li>
                            </ul>
                        </li>
                    }
                    @*@if (User.IsInRole("Manager"))
                    {
                    <li>@Html.ActionLink("Reports", "Index", "Report")</li>
                    }*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    @RenderSection("featured", false)
    <div class="container body-content">
        @RenderBody()
        <hr />
        <div class="row">
            <div class="col-md-9">
                <p>&copy; @DateTime.Now.Year  Dimension Data All Rights Reserved</p>
            </div>
            <div class="col-md-3 float-right">
                <img src="~/Content/images/logo.png" style="float: right;" />
            </div>
        </div>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

DDS.WebApp.PSQuoteGenerator/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Dimension Data PS Quote Generator</title>
    @Styles.Render("~/bundles/css")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Scripts")

    <meta name="description" content="Dimension Data PS Quote Generator" />
</head>
<body>

    @RenderSection("featured", false)
    <div class="container body-content">
        @RenderBody()
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

DDS.WebApp.PSQuoteGenerator/Views/Shared/_PdfLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MvcRazorToPdf</title>
    <style>
        html {
            font-family: Arial;
        }

        h1 {
            color: blue;
        }

        table {
            border: 1px solid black;
            border-spacing: 0px;
        }

            table tr th {
                background-color: gray;
                color: white;
                padding: 2px;
            }

            table tr td {
                margin: 0px;
                padding: 2px;
            }
    </style>
</head>
<body>
    @RenderBody()
</body>
</html>